# Generated by Django 3.2.13 on 2022-04-25 13:28

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(help_text='Tag for ToDo', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ToDoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_item', models.CharField(help_text='Add Task to list', max_length=150)),
                ('complete', models.BooleanField(default=False, help_text='Task is completed or not')),
            ],
        ),
        migrations.CreateModel(
            name='TodoTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myToDo.tags')),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myToDo.todoitem')),
            ],
        ),
        migrations.AddField(
            model_name='todoitem',
            name='tags',
            field=models.ManyToManyField(through='myToDo.TodoTags', to='myToDo.Tags'),
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(help_text='Note about a task')),
                ('date_created', models.DateTimeField(default=datetime.datetime.now, help_text='Note Creation Date & Time Stamp')),
                ('task', models.ForeignKey(help_text='Attach note to associated task', on_delete=django.db.models.deletion.CASCADE, to='myToDo.todoitem')),
            ],
        ),
    ]
