# Generated by Django 3.2.13 on 2022-04-26 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myToDo', '0002_auto_20220426_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='tag',
            field=models.CharField(help_text='Tag for Task', max_length=50),
        ),
        migrations.AlterField(
            model_name='todotags',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myToDo.tags'),
        ),
    ]
