# Generated by Django 3.2.13 on 2022-04-26 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myToDo', '0003_auto_20220426_2117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todotags',
            old_name='tag',
            new_name='tags',
        ),
        migrations.RenameField(
            model_name='todotags',
            old_name='todo',
            new_name='todoitem',
        ),
    ]
