# Generated by Django 3.2.13 on 2022-04-27 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myToDo', '0004_auto_20220426_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='tag',
            field=models.CharField(help_text='Tag for Task', max_length=50, unique=True),
        ),
    ]
