# Generated by Django 3.2.13 on 2022-04-27 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myToDo', '0005_alter_tags_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='tag',
            field=models.CharField(default=True, help_text='Tag for Task', max_length=50),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='list_item',
            field=models.CharField(default=True, help_text='Add Task to list', max_length=150),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='tags',
            field=models.ManyToManyField(default='None', through='myToDo.TodoTags', to='myToDo.Tags'),
        ),
    ]
