# Generated by Django 3.2.13 on 2022-04-27 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myToDo', '0006_auto_20220427_0213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tags',
            old_name='tag',
            new_name='tags',
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='tags',
            field=models.ManyToManyField(through='myToDo.TodoTags', to='myToDo.Tags'),
        ),
    ]
